### ISSUE TITLE
AssetsManagerExTest takes long time to load and shows different pictures for Universal and WP8 builds

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#100]
1. Used wp8.1-universal branch, built and ran cpp tests from Universal App sln and WP8 sln.
2. Select Etensions > AssetsManagerExTest
3. Clicking on the right arrow go though the tests in this group: each test shows a different picture

Actual result: Getting different behavior depending on the build and the device:
 - Lumia 820: 3 pictures for both solutions, same for both solutions, load time of the test is OK, I can barely see the cocos icon and % sign;
 - Lumia 1520: 3 pictures for WP8 build, 2 other pictures for Universal app build. Load time is pretty slow, about 30-60 seconds for the next picture to load while it shows the progress in % 
 - Surface pro Universal app build only: 2 pictures in the test suite. First load took about 2 minutes, after that moving to the next test takes about 5-10 sec.

**Comment by SvDyer** [comment]
The issue is back, the test is slow to load with intermitten crashes.
Especially noticeable on lower-end device (Lumia 820). The test also crashed once Lumia 1520 (on first launch) but was working fine afterwards.

**Comment by stammen** [comment]
Fixed in v3.7
