### ISSUE TITLE
[cocos2d-x v3.2] Screen cuts from both sides 

### ISSUE THREAD

**Issue by muhammad-arslan** [MSOpenTech/cocos2d-x#112]
Hello

I'm having issue that my game is not viewing in full screen. I'm sharing the screenshot. Is there any way to fix this. I am using cocos v3.2

![screenshot](https://cloud.githubusercontent.com/assets/5907758/5558355/e10a5f24-8d45-11e4-8d6b-8d414f385a89.png)

Thanks

**Comment by stammen** [comment]
In Windows Phone 8.0 there is a DirectX bug that does not allow ResolutionPolicy::NO_BORDER. You need to do something like:

    // Set the design resolution
#if (CC_TARGET_PLATFORM == CC_PLATFORM_WP8)
    // a bug in DirectX 11 level9-x on the device prevents ResolutionPolicy::NO_BORDER from working correctly
    glview->setDesignResolutionSize(designResolutionSize.width, designResolutionSize.height, ResolutionPolicy::SHOW_ALL);
#else
    glview->setDesignResolutionSize(designResolutionSize.width, designResolutionSize.height, ResolutionPolicy::NO_BORDER);
#endif

**Comment by muhammad-arslan** [comment]
Resolution policy is already ResolutionPolicy::SHOW_ALL.
Is there a way to show scene in fullscreen?

**Comment by stammen** [comment]
There is a bug in the WP8 directx driver that cannot support this. This is fixed in the cocos2d-x v3.x Universal App projects (Windows 8.1 and Windows Phone 8.1)
