### ISSUE TITLE
A few tests for default behavior under "Node: UI" crash WP8 build

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#113]
Pre-requisites: v3 brahch, WP8 build, Nokia Lumia 820 and 1520

1. Run CPP tests 
2. Select menu Node: UI > GUI Dynamic Create Test > ButtonTest > Click on the arrow to go back to UIButtonDisableDefaultTest 
3. GUI Dynamic Create Test > CheckBoxTest > Click on the arrow to go to UICheckBoxDefaultBehaviorTest
4. GUI Dynamic Create Test >SliderTest > Click on the arrow to go to UISliderDisabledDefaultTest

Actual result: cpp test app crashes on steps 2, 3, 4

Note: The tests work fine in the Universal app build

**Comment by stammen** [comment]
Fixed in pull request https://github.com/cocos2d/cocos2d-x/pull/10053. There was a missing precompiled shader for WP8.

**Comment by SvDyer** [comment]
Verified in v3 branch: the issue is fixed now.
