### ISSUE TITLE
Crash when enabling accelerometer

### ISSUE THREAD

**Issue by diamond-msc** [MSOpenTech/cocos2d-x#116]
Calling `Device::setAccelerometerEnabled(true);` on my Windows 8 box crashes with "element not found":
```
First-chance exception at 0x761E4598 (KernelBase.dll) in HelloCpp.Windows.exe: 0x40080202: WinRT transform error (parameters: 0x80070005, 0x80070490, 0x00000019, 0x07FAF08C).
First-chance exception at 0x761E4598 in HelloCpp.Windows.exe: Microsoft C++ exception: Platform::COMException ^ at memory location 0x07FAF528. HRESULT:0x80070490 Element nicht gefunden.
WinRT information: Element nicht gefunden.
Stack trace:
 >[External Code]
 >libcocos2d_v3.4_Windows_8.1.dll!cocos2d::Device::setAccelerometerInterval(float interval) Line 174
 >libcocos2d_v3.4_Windows_8.1.dll!cocos2d::Device::setAccelerometerEnabled(bool isEnabled) Line 82
...
```
https://github.com/MSOpenTech/cocos2d-x/blob/v3/cocos/platform/winrt/CCDevice.cpp#L174

My device has an orientation sensor, but probably no acceleration sensor. (Update: it has one)
Expected behavior: It should do nothing. (In the source I see a message box call, but this is also not what I expect, since I'm not aware of any `hasAccelerator` in cocos2d.)

**Comment by diamond-msc** [comment]
I must correct myself. According to the Store app "Sensor List" I discovered I have a working accelerometer :smiley:
"Tablet tester" crashes when testing the accelerometer, so it seems to be a quirky one.

**Comment by stammen** [comment]
What is your "Windows 8 box?"

**Comment by diamond-msc** [comment]
http://www.asus.com/Tablets_Mobile/Eee_Slate_EP121/

**Comment by stammen** [comment]
Which project are you building? Also is it from the v2 or v3 branch? Are you building a Universal App version?

**Comment by diamond-msc** [comment]
v3 head 2c5d82d772ea0f81bac46a7214fffb812a2a3652
I'm building the Win 8.1 part of a Universal App
reproducible with the HelloCpp test by inserting
`Device::setAccelerometerEnabled(true);`
at Line 75 of tests\cpp-empty-test\Classes\HelloWorldScene.cpp

**Comment by stammen** [comment]
I build the sample according to your instructions and it runs fine on my Dell Venue 8. 

Are you able to run the following accelerometer sample from MSDN on your device?

https://code.msdn.microsoft.com/windowsapps/Accelerometer-Sensor-Sample-22982671

**Comment by diamond-msc** [comment]
The sample crshes, too.
If I remove calls to `accelerometer->ReportInterval = x`, it works.
This seems to be a device specific issue :cry: , see http://forum.unity3d.com/threads/platform-comexception-at-memory-location-0x0669fab0-hresult-0x80070490-element-not-found.287062/

**Comment by stammen** [comment]
Add a try/catch around accelerometer->ReportInterval and see if it run.

**Comment by diamond-msc** [comment]
Works:
```c++
		try {
			accelerometer->ReportInterval = desiredReportInterval;
		}
		catch (Platform::COMException^)
		{
			// Something went wrong, continue
		}
```

**Comment by stammen** [comment]
I added the following to Device::setAccelerometerInterval() in CCDevice.cpp

        try {
            int minInterval = sAccelerometer->MinimumReportInterval;
            int reqInterval = (int) interval;
            sAccelerometer->ReportInterval = reqInterval < minInterval ? minInterval : reqInterval;
        }
        catch (Platform::COMException^)
        {
            CCLOG("Device::setAccelerometerInterval not supported on this device");
        }

Would you please try this code with your device?

**Comment by diamond-msc** [comment]
Looks good!
Tested with the Chipmunk test.
Gravity is the wrong way when the display is rotated 180 deg. No idea if that's another device specific one?

**Comment by stammen** [comment]
Fixed in pull request https://github.com/cocos2d/cocos2d-x/pull/10081

**Comment by stammen** [comment]
@diamond-msc Gravity fix is now part of the V3 branch of https://github.com/cocos2d/cocos2d-x

Please reopen if you find any issues. Thanks for your help with this issue!

**Comment by diamond-msc** [comment]
Can't reopen, so I'm just commenting:

Things got worse with Windows 10. The first exception is now thrown on `Accelerometer::GetDefault()`.

Did this to 'fix' the issue. I. e. no accelerator on Win 10: :cry: 

```c++
      try {
        sAccelerometer = Accelerometer::GetDefault();
      }
      catch (Platform::COMException^)
      {
        CCLOG("Device::setAccelerometerInterval not supported on this device");
      }
```
