### ISSUE TITLE
Universal app cpp tests crashing on tablet

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#117]
Several cpp tests crashing on tablet (Surface Pro) with same error which does not reproduce on Windows Phone:
Tested on v3 of MS Open Tech repo

Tests that crash:
1) Allocator - Basic;
2) Event Dispatcher > Add and remove listener when dispatching event
3) File Utils > FileUtils: check whether the file exists

![image](https://cloud.githubusercontent.com/assets/6464667/5730729/9dab9460-9b31-11e4-9486-4f4657de6b0a.png)

**Comment by stammen** [comment]
Did you open an issue?

Thanks,

Dale

**Comment by stammen** [comment]
This is now fixed in our v3 branch and the v3 branch of the main cocos2d-x repo.

**Comment by SvDyer** [comment]
Verified, the issue does not reproduce now.
