### ISSUE TITLE
"Draw primitives" test crashing

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#118]
"Draw primitives" test in "Node: Draw" crashes when using arrows to open it. 
Reproduces in Universal app on phone (Lumia 1520 and Lumia 820), but no such issue on tablet or in WP8 solution.

1. Build v3 branch Universal app (Phone) and run cpp-tests
2. Go to "Node: Draw" from the menu > "draw primitives" test opens by default without any issues
3. Use arrows to move through the tests

Actual result: the next test opens fine but on return to the "draw primitives" test, the app crashes

**Comment by stammen** [comment]
See pull request https://github.com/cocos2d/cocos2d-x/pull/10053 for more info. Windows Phone 8.1 is not correctly supporting glPointSize. This will be fixed in Angle in a few weeks.

**Comment by stammen** [comment]
The pull request seems to fix the crash. I will let you know when cocos2d-x pulls it to v3.

**Comment by SvDyer** [comment]
Verified: the issue is fixed.
