### ISSUE TITLE
TTF Label with stroke is not supported

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#124]
Just noticed that TTF Label with stroke is not supported on Windows or WP8:
![image](https://cloud.githubusercontent.com/assets/6464667/5930307/d00c0aea-a642-11e4-82fc-79923a73dff9.png)

This is how this looks on Android: 
![image](https://cloud.githubusercontent.com/assets/6464667/5930315/e3876538-a642-11e4-85df-5eb34fa4282f.png)

**Comment by stammen** [comment]
This is using the deprecated label api.
