### ISSUE TITLE
[cocos2d-x v3 universal] Linking errors on using deprecated global variables

### ISSUE THREAD

**Issue by muhammad-arslan** [MSOpenTech/cocos2d-x#127]
Hello

I'm using cocos2d-x v3 universal when I use any deprecated global variable in HelloWorldScene e.g CCSizeZero defined in CCDeprecated.h

    CC_DEPRECATED_ATTRIBUTE extern const Size CCSizeZero;
. It gives me a linker error 

    error LNK2001: unresolved external symbol "class cocos2d::Size const cocos2d::CCSizeZero" (?CCSizeZero@cocos2d@@3VSize@1@B)	C:\code\v3-universal orignal\v3-universal\cocos2d-x\projects\MyGame\proj.win8.1-universal\App.WindowsPhone\HelloWorldScene.obj	MyGame.WindowsPhone

if I make it with CC_DLL it works fine

    CC_DEPRECATED_ATTRIBUTE extern const CC_DLL Size CCSizeZero;

is this a right way to use it or there is a better work around?

Thanks

**Comment by waqasanwar79** [comment]
Hello Arslan!

CC_DEPRECATED_ATTRIBUTE extern const Size CCSizeZero;  is now Deprecated

Use this instead.

cocos2d::Size::ZERO;

Thanks
