### ISSUE TITLE
template app fails Cert Kit tests for win 8.1

### ISSUE THREAD

**Issue by qjhd554** [MSOpenTech/cocos2d-x#128]
generate hello world Universal app from cocos console on windows 8.1 
build and run certification tests
Expected: Pass (except for the default icons)
Actual:
Supported API test

FAILED
    Supported APIs

    Error Found: The supported APIs test detected the following errors:
        API FormatMessageA in kernel32.dll is not supported for this application type. libcurl.dll calls this API.
    Impact if not fixed: Using an API that is not part of the Windows SDK for Windows Store apps violates the Windows Store certification requirements.
    How to fix: Review the error messages to identify the API that is not part of the Windows SDK for Windows Store apps. Please note, C++ apps that are built in a debug configuration will fail this test even if it only uses APIs from the Windows SDK for Windows Store apps. See the link below for more information:
    Alternatives to Windows APIs in Windows Store apps.

**Comment by SvDyer** [comment]
This is still failing in 3.5 release, although was fixed in v4.

**Comment by stammen** [comment]
Still waiting for a pull request for the V3 dependencies to be merged.

**Comment by stammen** [comment]
Waiting for a pull request to be merged with the fix for 3.5


Sent by Outlook<http://taps.io/outlookmobile> for Android



On Tue, Mar 3, 2015 at 4:33 PM -0800, "SvDyer" <notifications@github.com<mailto:notifications@github.com>> wrote:


This is still failing in 3.5 release, although was fixed in v4.

-

**Comment by stammen** [comment]
This is fixed in the latest v3 branch of both the msopentech and cococ2d-x repos.
