### ISSUE TITLE
"Shader: Frag shader" tests are disabled on all platforms in Universal app

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#129]
"Shader: Frag shader" tests look disabled (black screen only) both on Windows and WP8.1 platforms in Universal app.

Tested on v4-develop branch. 

The tests for the Frag shader (Mandelbrot shader with Zoom and Julia shader tests) used to work correctly on Windows platform (Surface and Desktop) in earlier versions.

**Comment by stammen** [comment]
No longer working on v4. Closing for now.
