### ISSUE TITLE
MSVCRT link warning in universal builds

### ISSUE THREAD

**Issue by qjhd554** [MSOpenTech/cocos2d-x#130]
- sync latest code and build

Expected: no link warnings
Actual: LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library

**Comment by stammen** [comment]
@qjhd554 I will give this a try:

https://msdn.microsoft.com/en-us/library/aa267384(v=vs.60).aspx

**Comment by stammen** [comment]
Fixed in pull request https://github.com/cocos2d/cocos2d-x/pull/12168
