### ISSUE TITLE
ControlSwitchTest crashes on Lumia 1520

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#131]
Tested on v4-develop branch (cocos2d/cocos2d-x)
The issue occurs only on Lumia 1520 (Lumia 820 and Windows Surface do not have this issue)

1. Build and run cpp-tests
2. Go to Extensions > CCControlButtonTest > ControlSwitchTest 

The app blinks and then crashes.

**Comment by stammen** [comment]
We are no longer working on v4.
