### ISSUE TITLE
"The desired name for cpp is invalid" error

### ISSUE THREAD

**Issue by msaad99** [MSOpenTech/cocos2d-x#132]
I just downloaded the cocos2dx-v2-universal and I'm trying to add my existing files to the ProjectName.Shared project in the classes folder but I get the error:
"The desired name for xxx.cpp file is invalid"
This is happening for every file that I try to add in this project. 

![screenshot 2015-03-01 16 29 38](https://cloud.githubusercontent.com/assets/4525511/6430546/8a4a023e-c030-11e4-8e96-fb04353e9b05.png)

**Comment by stammen** [comment]
I have not seen that error before. What version of Visual Studio are you using?

**Comment by msaad99** [comment]
visual studio 2013 update 4. I have never seen this myself either. Can't even find anything on Google. I downloaded again and then tried but same error occurred.

**Comment by stammen** [comment]
@msaad99 Were you able to resolve this issue? Please reopen the issue if you are still having this problem.

**Comment by 15100103** [comment]
No I was not able to resolve it. Haven't tried tackling it since then.

**Comment by msaad99** [comment]
No I was not able to resolve it. Haven't tried tackling it since then.
