### ISSUE TITLE
Label Receives Keyboard Event test does not work in Universal App on Windows

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#134]
1. Build and run cpp-tests.Windows (v3)
2. Run the tests on desktop
3. From the main menu go to EventDispatcher > Label Receives Keyboard Event 
4. Press some keys on the keyboard

Actual result: Nothing happens (No keyboard event received!)
Expected result: Message should change to "Key xxx pressed/released" as user types on the keyboard. 
Note: this is working correctly in Win32 cocos build.

**Comment by iacopocheccacci** [comment]
I have the same issue. 
I use "EventListenerKeyboard" in my project and it seems not to receive "onKeyPressed" and "onKeyReleased" callbacks.

**Comment by stammen** [comment]
Fixed in pull request https://github.com/cocos2d/cocos2d-x/pull/11802

**Comment by stammen** [comment]
Fixed in the v3 branch of cocos2d-x or msopentech. Please reopen if this is still an issue.
