### ISSUE TITLE
Particle Demo / Lines test: lines go horizontally in Universal App on Phone

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#135]
1. Build and run cpp-tests.WindowsPhone 
2. From the main menu go to Node: Particles > Particle Demo / lines

Actual result:
Particle Demo / Lines test: lines go horizontally in Universal App on Phone but on all other platforms they go vertically
Universal App on Phone: 
![image](https://cloud.githubusercontent.com/assets/6464667/6721580/e778d0bc-cd8b-11e4-983f-fe797636aa3a.png)

WP8, Universal App on Windows, Android:
![image](https://cloud.githubusercontent.com/assets/6464667/6721588/0f586476-cd8c-11e4-980e-be631640fbd6.png)

**Comment by stammen** [comment]
Works correctly in the latest version v3.7.
