### ISSUE TITLE
SimpleAudioEngine in v2-universal does not support sound files in subdirectories

### ISSUE THREAD

**Issue by yonomitt** [MSOpenTech/cocos2d-x#139]
Unlike the SimpleAudioEngine in the win32 directory, the versions in wp8, win-8.1 and winrt do not search in subdirectories added via CCFileUtils::setSearchResolutionsOrder

**Comment by stammen** [comment]
Fixed in pull request https://github.com/MSOpenTech/cocos2d-x/pull/140
