### ISSUE TITLE
[v3.6-universal-win8.1-cpptests]Node: UI-->GUI Dynamic Create Test-->UISliderTest

### ISSUE THREAD

**Issue by stammen** [MSOpenTech/cocos2d-x#142]
https://github.com/cocos2d/cocos2d-x/issues/11605

Program is lagging so much when dragging the slider.

console log:
0x74A94DBD 处(位于 cpp-tests.Windows.exe 中)最可能的异常: Microsoft C++ 异常: IOException，位于内存位置 0x06F7E584 处。
0x74A94DBD 处(位于 cpp-tests.Windows.exe 中)最可能的异常: Microsoft C++ 异常: [rethrow]，位于内存位置 0x00000000 处。

**Comment by WenhaiLin** [comment]
Hi @stammen ,the 3.6 final release is planned for the day after tomorrow[2015.4.29].

**Comment by stammen** [comment]
I will look at this today.

**Comment by stammen** [comment]
Fixed in pull request https://github.com/cocos2d/cocos2d-x/pull/11622
