### ISSUE TITLE
Storage space is not freed up after cocos apps uninstall

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#144]
Steps:
1. Deploy cpp tests or a new cocos project to WP8.1 (reproduced on Lumia 820)
2. Note the Total storage space used on the phone
3. Uninstall the app and check storage space again

Actual result: Total space used remains unchanged after uninstalling the app although space used by Apps+Games goes down to the number it was before installation of the cocos app

**Comment by stammen** [comment]
Is this still an issue?

**Comment by SvDyer** [comment]
Yes, still reproduces in same way on Lumia 820. 
Note: this device does not have an SD card.

**Comment by stammen** [comment]
You need to click on phone in storage sense and then the numbers will eventually update.
