### ISSUE TITLE
The memory cost on wp8 is too high , why?

### ISSUE THREAD

**Issue by youchlucky** [MSOpenTech/cocos2d-x#147]
hi, stammen:

I'm glad to see there was someone to maintain this version of cocos2dx. but when I moved my game codes from iOS and Android onto wp8 used quick3.3 which based on cocos2dx 3.3, the memory cost reach up to 180M, which is below 100M on iOS and android. I found some small memory leaks in cocos2dx-3.3, but it has no work for the high memory cost. I want to know where the memory used for?

**Comment by stammen** [comment]
Are you doing a debug or release build? Please use the Windows 8.1 Universal App projects. WP8 uses twice the memory for textures.

**Comment by stammen** [comment]
What is quick3.3?

**Comment by youchlucky** [comment]
Thanks for your reply!
I use debug mode on wndows phone 8.0 app project. 
Quick3.3 is a version based of cocos2dx3.3 which is special for lua developer. 

As you say:"Please use the Windows 8.1 Universal App projects. WP8 uses twice the memory for textures."  It means that the texture on windowns 8.1 universal app projects cost memory will be half of it on Windows 8.0 app project?

**Comment by stammen** [comment]
Yes. The WP8 versions uses twice the memory. We no longer support WP8 after cocos2d-x v3.5.

**Comment by youchlucky** [comment]
Thank you very much!
