### ISSUE TITLE
HTTPRequest return error code 56

### ISSUE THREAD

**Issue by youchlucky** [MSOpenTech/cocos2d-x#148]
I use HTTPRequest to make a http request for "Get", but it always return error code 56 which indicates the msg  "Failure with receiving network data".  It's occurs on simulator. but it's ok on device. So I should debug my game always on device,  I check the network connection of the simulator, it 's ok to use IE. to show network. So really I don't know why?

**Comment by stammen** [comment]
You will probably need to try some of the items in this article. http://blog.siliconvalve.com/2012/09/26/fix-windows-8-and-hyper-v-virtual-switch-problems/

Please let use know if you were able to resolve the internet connectivity issue.
