### ISSUE TITLE
Tiles on Windows screen for cocos applications are missing names/text labels

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#149]
Only cpp-tests app tile has label on Windows screen.
js-tests, MyGame (new project), HelloCpp tiles look all the same without any text labels on them:
 
![image](https://cloud.githubusercontent.com/assets/6464667/7848083/7c6b4e52-047d-11e5-8875-5a1fabc8e753.png)

**Comment by stammen** [comment]
https://github.com/cocos2d/cocos2d-x/pull/12460

**Comment by SvDyer** [comment]
There are still no labels on Windows 10 tiles, not even for cpp-tests
![image](https://cloud.githubusercontent.com/assets/6464667/8319472/28894a08-19c4-11e5-8332-eb9bde646b6f.png)

**Comment by stammen** [comment]
Is this for WIndows 10?

**Comment by SvDyer** [comment]
Yes

**Comment by stammen** [comment]
VS2015 still does not have a app manifest editor. I will fix this with the next version of VS2015 for cocos2d-x v3.8

**Comment by stammen** [comment]
Fixed in cocos2d-x v3.8
