### ISSUE TITLE
Once uncached, restored audio doesn't play until one more "uncache"

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#151]
Once uncached, restored audio doesn't play until one more "uncache"
Repro for WindowsStore project
1. Run cpp-tests > Audio - NewAudioEngine
2. play an audio clip
3. delete/rename the audio file from resources in exe folder path (cocos2d-x\build\Release\cpp-tests.Windows\AppX\Assets\Resources)
4.play that audio clip again (without uncache) - plays as expected
5. Uncache and play - doesn't play which is expected
6. Restore the file deleted in step 3 - "Play" remains disabled
7. Click "stop" and then as Play is enabled, click on it 

Actual result: audio does not play with restored file
Note: Need to do "uncache" again and then the restored file plays successfully

**Comment by stammen** [comment]
@SvDyer Is this fixed?

**Comment by SvDyer** [comment]
Yes, this is fixed. Closing.
