### ISSUE TITLE
A link problem caused by luabinding on WP8.1-universal project

### ISSUE THREAD

**Issue by youchlucky** [MSOpenTech/cocos2d-x#152]
Hi, stammen two days ago, you suggested me to make a wp8.1 universal project to solve the high memory cost problem:

At next: I made a luabinding on my wp8.1 universal app project, Two link errors as followed:
1  lua-bindings.WindowsPhone.lib(loslib.obj) : error LNK2019: " Undefined external "_system" referred in _os_pushresult"
2  lua-bindings.WindowsPhone.lib(loslib.obj) : error LNK2019: " Undefined external "_getenv" referred in _os_pushresult"

I found them on wp8.0, the two symbols are all in MSVCRTD.lib which according dll is MSVCR110D.dll
but on wp8.1 the MSVCRTD.lib 's according dll is msvcr120d_app.dll, which doesn't include the two symbols above.
So, I have no way to solve this problem.

**Comment by youchlucky** [comment]
I'm sorry , I forgot to paste the code:

[frameworks\cocos2d-x\external\lua\lua\loslib.c]
static int os_execute (lua_State *L) {
  lua_pushinteger(L, system(luaL_optstring(L, 1, NULL)));
  return 1;
}

static int os_getenv (lua_State *L) {
  lua_pushstring(L, getenv(luaL_checkstring(L, 1)));  /* if NULL push nil */
  return 1;
}

**Comment by youchlucky** [comment]
In the two project setting's precompile define part:
they all include this sentence:"WINAPI_FAMILY=WINAPI_FAMILY_PHONE_APP"
but in stdlib.h, we can see getenv or system are all followed by macro _CRT_USE_WINAPI_FAMILY_DESKTOP_APP, but why it's ok in wp8.0, and not in wp8.1 universal app?

**Comment by stammen** [comment]
We don't officially support LUA in the Windows 8.1 Universal App.

**Comment by stammen** [comment]
Please create a new issue asking for Lua support for Windows 8.1/10 Universal Apps.
