### ISSUE TITLE
Update README file with Windows 10 information

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#155]
Need to update README file with Windows 10 information: build requirements and any other Win10-specific instructions.

**Comment by stammen** [comment]
Fixed in PR https://github.com/cocos2d/cocos2d-x/pull/12460

**Comment by SvDyer** [comment]
Readme file has separate sections for commands to build new project (Build and run... ) and Build Requirements section listing IDEs for each platform. 
For Windows 10 we now have build requirements inside the "build and run"  section.
The users will still find the info they need but doesn't look consistent with the rest of the document :)

**Comment by stammen** [comment]
This is fine for now.
