### ISSUE TITLE
Allow integrating windows SDK ads or other ads provider in universal app

### ISSUE THREAD

**Issue by Dredok** [MSOpenTech/cocos2d-x#157]
Ads SDK needs to be added to a C# project (as far as I know), thus only the wp8-xaml solution can be used to integrate ads.

We need support for universal apps.

**Comment by stammen** [comment]
Microsoft Ad SDK works in the WIndows 8.1 Universal app starting with v3.6.

**Comment by Dredok** [comment]
I can put the ads in the XAML but then I do not know how to control it. I want to toggle the visibility: How can I enable / disable the banner? (ie. in gameplay I would like to hide the banner).

I have tried to instantiate it from C++ code but haven't achieve it. Could you tell me how I could enable/disable the banner from C++ code ?

Thanks
Dredok

**Comment by Dredok** [comment]
Okey finally I figured out how to do it. I do not know if its the more elegant way (i doubt it):
- create the adcontrol as a child of a grid in . Put it a name like for example "adcontrol" in OpenGLESPage.xaml file
- modify CocosRenderer .cpp and .h to get the adControl as a parameter when it is created.
- From CocosRenderer, control the app visibility. Make sure this runs on UI thread.

**Comment by tipking** [comment]
Dredok can you please upload a sample universal project with code please

**Comment by MukeshBharti** [comment]
Hi Dredok,
Can you please share  sample universal project with codes.

**Comment by BousaCZ** [comment]
I would appretitate this as well Dredok, could you please show us your codes for this?..
