### ISSUE TITLE
Compile Error: Undeclare identifier "IWinrtEglWindow" in "cocos\platform/wp8/CCGLViewImpl-wp8.h"

### ISSUE THREAD

**Issue by youchlucky** [MSOpenTech/cocos2d-x#158]
I made a project with cocos2dx-3.5, then open the sln in proj.win8.1-universal folder. Replace WINRT with WP8 in file  "cocos2d\cocos\2d\winrt_8.1_props\cocos2d_winrt_8.1.props".
As followed, I compile the project, then show the error below:

Undeclare identifier "IWinrtEglWindow" in "cocos\platform/wp8/CCGLViewImpl-wp8.h"

How I should to solve it ?

**Comment by stammen** [comment]
Why did you replace WinRT with WP8? You don't need to do that for the universal app.
