### ISSUE TITLE
CocoStudioSceneTest crashes cpp-tests app on Windows 10

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#159]
1. Run cpp tests on Windows 10
2. Go to Extensions > CocoStudioSceneTest 

Actual result: the app crashes with the error message:

Assertion failed!
Program: ...se\cpp-tests\AppX\libcocos2d_v3.7_Windows_10.0.dll
File:C:\Projects\cocos2d-x\external\json/document.h
Line:839
Expression: false

**Comment by stammen** [comment]
@SvDyer Please open this issue on the main cocos2d-x repo as it it also a bug on Win32.

**Comment by SvDyer** [comment]
Verified: this is no longer failing on Windows 10.
Note: tested Store version only, phone emulator keeps handing.
