### ISSUE TITLE
Audio - NewAudioEnging test freezes cpp-tests on Windows 10

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#160]
1. Run cpp tests on Windows 10
2. Go to Audio - NewAudioEnging test 
3. Click "play" and then click "stop"

Actual result: the audio stops playing but the cpp-tests app freezes with the play menu disabled and remains nonoperational until reopened.
Expected result: play should become enabled after the audio has stopped playing.

**Comment by stammen** [comment]
@SvDyer @anniruddh Has this issue been resolved?

**Comment by stammen** [comment]
I just verified this is still an issue on Windows 10. I will look into it.

**Comment by stammen** [comment]
This is fixed in the v3.7-release branch

**Comment by SvDyer** [comment]
Yes, this is fixed now, closing the issue.
