### ISSUE TITLE
Unable to enter text into Edit Box on Windows 10 Phone Emulator

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#161]
1. Run cpp tests on Windows 10 Phone Emulator
2. Go to Node: UI > GUI Dynamic Create Test > EditBox Test
3. Click on one of the fields Name/Password/Email and try to enter some text into those fields

Actual result: There is no text field with Done and Cancel button that should appear and selected letters are not entered anywhere

Windows 10 on Phone Emulator:
![image](https://cloud.githubusercontent.com/assets/6464667/8096379/6abdc0e0-0f8b-11e5-84c2-0f255ce2914c.png)

Expected: should behave like on all other environments (desktop Windows 10 and Windows 8.1 on Phone Emulator work fine):
 
![image](https://cloud.githubusercontent.com/assets/6464667/8096411/bba2f174-0f8b-11e5-80a0-5aba7b21704e.png)

**Comment by stammen** [comment]
This also happens on the Windows 10 Phone device.  The textbox is being drawn but it is behind the keyboard.

Since Windows 10 Phone is not stable yet I won't fix this until the next update.

**Comment by stammen** [comment]
Fixed in cocos2d-x v3.8
