### ISSUE TITLE
Will the UWP (Windows 10) templates be added to cocos2dx 2.2.6?

### ISSUE THREAD

**Issue by vick-joingame** [MSOpenTech/cocos2d-x#164]
Hello. Windows 10 is coming soon, so will the UWP (Windows10) support added to cocos2dx v.2.2.6 branch? Thanks

**Comment by stammen** [comment]
The work to do this is currently not scheduled. We will try to get it on the schedule for July.

**Comment by stammen** [comment]
Windows 10 UWP upport is currently on the v2.2.6-uwp branch. It will be merged into the v2.2.6-universal branch when I am done testing.
