### ISSUE TITLE
Particle Demo test crashes cpp-tests on windows phone 8.1

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#165]
1. Run cpp-tests on Windows Phone 8.1 (this issue does not reproduce for Windows Store project)
2. From the main menu go to Node: Particles
3. Tap on the left arrow to get to the Particle Demo test (you should see two Particle Emitters using different texture). 
4. Tap left/right arrow to move to the another text

Actual result: the app crashes

Note: The issue will also reproduce using the right arrow in step 3, it will just take more taps to get to this test. The result however is same: The Particle Demo test opens successfully and then the app crashes when trying to move to a next test.

**Comment by stammen** [comment]
@SvDyer Does this test crash on Win32?

**Comment by SvDyer** [comment]
Yes, it crashes on Win32. And actually it also crashes in Windows Store version, which I did not see reproduce yesterday but it does.
