### ISSUE TITLE
cpp-tests[ win8.1-universal--window 8.1]:Audio - CocosDenshion:Crash when no audio device on PC

### ISSUE THREAD

**Issue by stammen** [MSOpenTech/cocos2d-x#168]
Audio playback will crash in the Windows 8.1 Store App if there is no audio device on the PC (or all of the audio devices have been disabled.

How to reproduce:

1. Disable all audio playback devices on the pc.
2. Try to play audio with any of the cpp audio tests
3. App will crash at either

m_musicEngine->CreateMasteringVoice()

or

XAudio2Create()

https://github.com/cocos2d/cocos2d-x/issues/12448#issuecomment-113546852

FYI: To reenable audio device http://answers.microsoft.com/en-us/windows/forum/windows_vista-pictures/after-disabling-the-speakers-in-sound-control/df4e5343-e708-49c2-8fde-97192a7a21c6

**Comment by anniruddh** [comment]
This is fixed in v3-winrt-audio branch.

**Comment by stammen** [comment]
@SvDyer This is fixed in the latest v3 branch

**Comment by SvDyer** [comment]
Verified in 8.1 store app: does not crash with all audio devices disabled.
