### ISSUE TITLE
Store App certification test fails on Windows 10

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#170]
1. Create a new cocos project on Windows 10 run an app certification test for Store App
2. Review the test results:

There are currently 3 failures that should be addressed (reproduced on Windows Build 10130, VS 2015 RC Version 14.0.22823.1 D14REL)

1. FAILED Platform version launch test
No additional information for  Requirement: 10 Test: 81
◦[HRESULT: 0x800706BE]. Failed to invoke test operation: 'ExecuteTest'.
◦[HRESULT: 0x800706BA]. Failed to destroy 'Microsoft.Windows.SoftwareLogo.Tests.HighOSVersionLaunchCheck.HighOSVersionLaunchCheck'.

2. FAILED Supported APIs
• Error Found: The supported APIs test detected the following errors: ◦API XAudio2Create in xaudio2_9.dll is not supported for this application type. libcocos2d_v3.7_Windows_10.0.dll calls this API.
• Impact if not fixed:  Using an API that is not part of the Windows SDK for Windows Store apps violates the Windows Store certification requirements.  
• How to fix:  Review the error messages to identify the API that is not part of the Windows SDK for Windows Store apps. Please note, C++ apps that are built in a debug configuration will fail this test even if it only uses APIs from the Windows SDK for Windows Store apps. See the link below for more information: 
 Alternatives to Windows APIs in Windows Store apps. 

3. FAILED Type location test
• Error Found: The type location test detected the following errors: ◦The types in the cocos2d namespace are located in file C:\Projects\cocos2d-x\projects\MyGame\proj.win10\Release\MyGame\AppX\MyGame.winmd that does not match the namespace.
• Impact if not fixed:  Windows store doesn't allow apps that don't pass Windows Runtime Metadata Validation.  
• How to fix:  Please ensure that the metadata for all Windows Runtime types is located in the winmd file that has the longest namespace-matching name in the appx package.

**Comment by stammen** [comment]
Visual Studio C++ template projects also are currently failing WACK tests.

**Comment by stammen** [comment]
fixed in v3.8
