### ISSUE TITLE
Close ( I ) button doesn't work for js projects

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#171]
1. Build and run a new js project or js-tests app (reproduced same way for store and phone versions)
2. Click on the round close button (I) to close the app
![image](https://cloud.githubusercontent.com/assets/6464667/8366416/ba5f59b4-1b49-11e5-832d-d77da11c38a2.png)
 

Actual result: nothing happens
Expected: the app should close (this is working for cpp projects)

**Comment by stammen** [comment]
The button in the JS HelloWorld app is not designed to close. It just logs a message to the console.

**Comment by SvDyer** [comment]
what about this button in js-test? also not designed to close? 
![image](https://cloud.githubusercontent.com/assets/6464667/8366574/e1a76696-1b4a-11e5-8951-57024ae9b605.png)

**Comment by stammen** [comment]
Yes. They are just using the button. There are no close the app actions in js-tests.
