### ISSUE TITLE
Microsoft C++ Exception: Cn::XH, what's it?

### ISSUE THREAD

**Issue by youchlucky** [MSOpenTech/cocos2d-x#172]
My project is based on cocos2dx-3.3, Windows universal app project, in debug mode, I use a webview in OpenGLESPage.xaml file, which code is as below:

<Page
    x:Class="cocos2d.OpenGLESPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:cocos2d"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <SwapChainPanel x:Name="swapChainPanel">
        <Button x:Name="cocos2d_editbox" Visibility="Collapsed"  Height="0"  Margin="0,0,0,0">
            <Button.Flyout>
                <Flyout x:Name="cocos2d_editbox_flyout">
                    <Grid VerticalAlignment="Top" x:Name="cocos2d_editbox_grid">
                        <Button x:Name="cocos2d_editbox_done" Width="120" Visibility="Visible" Content="确定" HorizontalAlignment="Right" Margin="50,0,120,0" Grid.Row="1" VerticalAlignment="Top"/>
                        <Button x:Name="cocos2d_editbox_cancel"  Width="120" Visibility="Visible"  Content="取消" HorizontalAlignment="Right" Margin="120,0,0,0" Grid.Row="1" VerticalAlignment="Top"/>
                        
                    </Grid>
                </Flyout>
                
            </Button.Flyout>
        </Button>
        <WebView x:Name="project_webview" HorizontalAlignment="Center" Visibility="Visible" Height="100" VerticalAlignment="Center" Width="100" />

    </SwapChainPanel>
</Page>

When it runs on simulator 8.1 WVGA 4 inch 512MB, the output windows show many error tips as followed:

0x76EE210B 处(位于 sanguohero_pack.WindowsPhone.exe 中)最可能的异常: Microsoft C++ 异常: Cn::XH，位于内存位置 0x045CF34C 处。
0x76EE210B 处(位于 sanguohero_pack.WindowsPhone.exe 中)最可能的异常: Microsoft C++ 异常: Cn::XH，位于内存位置 0x045CF34C 处。
0x76EE210B 处(位于 sanguohero_pack.WindowsPhone.exe 中)最可能的异常: Microsoft C++ 异常: Cn::XH，位于内存位置 0x045CF34C 处。
0x76EE210B 处(位于 sanguohero_pack.WindowsPhone.exe 中)最可能的异常: Microsoft C++ 异常: Cn::XH，位于内存位置 0x045CF34C 处。
0x76EE210B 处(位于 sanguohero_pack.WindowsPhone.exe 中)最可能的异常: Microsoft C++ 异常: Cn::XH，位于内存位置 0x045CF34C 处。
0x76EE210B 处(位于 sanguohero_pack.WindowsPhone.exe 中)最可能的异常: Microsoft C++ 异常: Cn::XH，位于内存位置 0x045CF34C 处。
0x76EE210B 处(位于 sanguohero_pack.WindowsPhone.exe 中)最可能的异常: Microsoft C++ 异常: Cn::XH，位于内存位置 0x045CF34C 处。
0x76EE210B 处(位于 sanguohero_pack.WindowsPhone.exe 中)最可能的异常: Microsoft C++ 异常: Cn::XH，位于内存位置 0x045CF34C 处。
0x76EE210B 处(位于 sanguohero_pack.WindowsPhone.exe 中)最可能的异常: Microsoft C++ 异常: Cn::XH，位于内存位置 0x045CF34C 处。
0x76EE210B 处(位于 sanguohero_pack.WindowsPhone.exe 中)最可能的异常: Microsoft C++ 异常: Cn::XH，位于内存位置 0x045CF34C 处。
0x76EE210B 处(位于 sanguohero_pack.WindowsPhone.exe 中)最可能的异常: Microsoft C++ 异常: Cn::XH，位于内存位置 0x045CF34C 处。
... ...

I don't know what's it it? how to solver it?

**Comment by stammen** [comment]
It is a problem with the windows phone emulator.If you simply create a C++ Blank App universal app project using the Visual Studio new project template you will get the same errors when you add the webview to the xaml.

**Comment by youchlucky** [comment]
You mean that I have no need to care of it?

**Comment by stammen** [comment]
That is correct.
