### ISSUE TITLE
How to position the windows control accurately?

### ISSUE THREAD

**Issue by youchlucky** [MSOpenTech/cocos2d-x#173]
I add a webview control in my windows universal app project. when position the control, the Windows::UI::Xaml::Thickness object is very hard to position the control.
My target  is to position is like this:
![test1](https://cloud.githubusercontent.com/assets/12620726/8400706/97341a10-1e55-11e5-9cc1-7c392d684576.png)

frameSize: 400*666, I  want to position the control at center(200, 380) with size(300, 350), so I make a Windows::UI::Xaml::Thickness object with parameters: (100, 111, 100, 145)
111= (666 - (320 + 350/2)
205= (380- 350/2)

But result is like this:
![test2](https://cloud.githubusercontent.com/assets/12620726/8400707/9bb5dbe6-1e55-11e5-897e-f957984543c5.png)

then I adjust many parameters, the position of webview, is always wrong. Why of this? Why to design so puzzled interface.   May I have other ways to control the position of webview.

**Comment by stammen** [comment]
How about using Margin?

        <WebView x:Name="webView1" Source="http://cocos2d-x.org/"  Margin="50,50,50,100"/>

**Comment by youchlucky** [comment]
I just use Margin, but the position is always wrong.

**Comment by stammen** [comment]
Please send me your xaml.

**Comment by youchlucky** [comment]
Addition, whether I should to calc the number in Margin with cocos2d::Director::getInstance()->getWinSize() or cocos2d::GLViewImpl::sharedOpenGLView()->getFrameSize()?

**Comment by stammen** [comment]
Is it possible for you to see me a code sample?

**Comment by youchlucky** [comment]
Please give me your email, I will send you a sample .

**Comment by stammen** [comment]
dalestam@microsoft.com

**Comment by youchlucky** [comment]
Thank you very much, I have solved this problem.
