### ISSUE TITLE
Cocos2d-js hasOwnProperty('keyboard') returns false on windows phone 8.1

### ISSUE THREAD

**Issue by harrysjoerd** [MSOpenTech/cocos2d-x#176]
When implementing the back button for windows phones in cocos2d-js I found  that the function cc.sys.capabilities.hasOwnProperty('keyboard') returns false. However, we should check for the back button through a keyboard listener, so I expedt this function call to return true.

**Comment by stammen** [comment]
EventTest.js in js-tests/src uses

        if ('keyboard' in cc.sys.capabilities) 

Does that work for you?
