### ISSUE TITLE
Thread safely call in winrt?

### ISSUE THREAD

**Issue by youchlucky** [MSOpenTech/cocos2d-x#178]
My project is based on cocos2dx3.3-lua。 When game start, I init some ui by the function call as followed:

Windows::UI::core::CoreDispatcher^ dispatcher = Windows::ApplicationModel::core::CoreApplication::MainView->CoreWindow->Dispatcher;
dispatcher->RunAsync(Windows::UI::Core::CoredispatcherPriority::Normal, ref new Windows::UI::Core::DispachedHandler([=]() -> void 
{
     // some ui init call
    ... ... 

   // Here we make a callback function calling to cocos2dx
    function1();
}));

In function1, we always received some strange exception which would not occur when we directorly call it without in the Winrt UI thread.

Then I want to know how to call the cocos2dx functions in winrt ui thread safely?

**Comment by stammen** [comment]
You can't call cocos2d-x functions from the ui thread. You must call them from the rendering thread.
What are you doing in the ui init call?

Look at how pointer events are handled to see how you need to queue them to the rendering thread. You will need to do something similar.

**Comment by youchlucky** [comment]
Thanks very much!
