### ISSUE TITLE
Win10 Project can't be debugged as  LocalMachine or simulator mode. 

### ISSUE THREAD

**Issue by cnsoft** [MSOpenTech/cocos2d-x#187]
Win10 Project can't be debugged as  LocalMachine or simulator mode. 
check the log: 
“'hellowin10.exe' (Win32): Loaded 'D:\cocos2d-x-3.10-winrt-fix\hellowin10\proj.win10\Debug\hellowin10\AppX\hellowin10.exe'. Symbols loaded.
'hellowin10.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntdll.dll'. Cannot find or open the PDB file.
'hellowin10.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel32.dll'. Cannot find or open the PDB file.
'hellowin10.exe' (Win32): Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. Cannot find or open the PDB file.
'hellowin10.exe' (Win32): Loaded 'C:\Windows\SysWOW64\combase.dll'. Cannot find or open the PDB file.
'hellowin10.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcrt.dll'. Cannot find or open the PDB file.
'hellowin10.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rpcrt4.dll'. Cannot find or open the PDB file.
'hellowin10.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sspicli.dll'. Cannot find or open the PDB file.
'hellowin10.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cryptbase.dll'. Cannot find or open the PDB file.
'hellowin10.exe' (Win32): Loaded 'C:\Windows\SysWOW64\bcryptprimitives.dll'. Cannot find or open the PDB file.
'hellowin10.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sechost.dll'. Cannot find or open the PDB file.
The thread 0x2070 has exited with code -1073741515 (0xc0000135).
The thread 0x22a4 has exited with code -1073741515 (0xc0000135).
The program '[1112] hellowin10.exe' has exited with code -1073741515 (0xc0000135) 'A dependent dll was not found'.” 

i use clean source code downloaded from branch cocos2d-x-3.10-winrt-fix . 
win10 version is 10586. vs2015 Enterprise update1 .  additional info, i can run debug with  windows phone emulator.

**Comment by stammen** [comment]
@cnsoft Please don't use the branches on the MSOPenTech repo. They are for pull requests to the main cocos2d-x repo. Please use the v3.10 branch at https://github.com/cocos2d/cocos2d-x or downloaded the code from http://cocos2d-x.org/download, I just downloaded v3,10 and ran a debug x86 build of a new project on the desktop and it worked fine. Please let me know if you continue to have problems.

Here is the result of building a new project win v3.10::

![image](https://cloud.githubusercontent.com/assets/1226490/12851920/4d30acdc-cbe1-11e5-8c85-ea6907190b2d.png)

**Comment by cnsoft** [comment]
Actually, i have tried first from 3.10 official code ( installed with cocos installer) , it failed, then i want to try this branch here.  Since your code works fine, i will try download from website once more again , sorry to trouble you.

**Comment by stammen** [comment]
@cnsoft Please let me know if it works for you.

**Comment by cnsoft** [comment]
unluck for me. it still can't work.  
log show that  'A dependent dll was not found'.” .  not sure what it is. i just update the vs2005 update 1.  
any suggestion? 

![20160206111743](https://cloud.githubusercontent.com/assets/32758/12856633/d1fc86b2-cc80-11e5-9cf3-c9559c838f1f.png)
![20160206112029](https://cloud.githubusercontent.com/assets/32758/12856645/dfe81304-cc80-11e5-9005-368483eb5784.png)

**Comment by stammen** [comment]
@cnsoft Please send me your project so I can take a look.

**Comment by cnsoft** [comment]
ok. wait .please  rename the hellowin10.png to  hellowin10.rar.  not include  cocos2d folder. 

![hellowin10](https://cloud.githubusercontent.com/assets/32758/12857575/f02045d4-cc85-11e5-93e4-dcd70b1da154.png)

**Comment by stammen** [comment]
@cnsoft I was able to build and run it with cocos2d-x v3.10. How exactly did you create the project? What URL did you download the cocos installer from?

**Comment by cnsoft** [comment]
http://cocostudio.download.appget.cn/Cocos2D-X/cocos2d-x-3.10.zip   is just i download url. 

i create the project with cocos console.  like this command:   cocos new  hellowin10 -l cpp

**Comment by stammen** [comment]
@cnsoft Please use http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip. Windows 10 UWP is not yet integrated with cocos studio. Make sure you run setup.py and restart your console window before creating a new project.

**Comment by cnsoft** [comment]
@stammen   ok. so let me try  run setup.py now. and check again. 

i am not sure ,  it is my develop machine environment issue.  i install win10 with bootcamp in my macbook.

**Comment by cnsoft** [comment]
@stammen , i got it work after  i move the project to the bootcamp disk (NTFS format)  from my external usb disk ( exFat format ). then  i only change the output dir to bootcamp disk, it can works also.   

so it should be the develop environment issue. though the error log is not friendly enough .

**Comment by stammen** [comment]
Interesting. Thanks for letting me know.
