### ISSUE TITLE
support for Windows Imaging Component

### ISSUE THREAD

**Issue by qjhd554** [MSOpenTech/cocos2d-x#27]
clean up design to leverage WIC, instead of source tree dependency on binary libs such as 

•	libjpeg
•	libpng

**Comment by stammen** [comment]
WIC support added in pull requests

https://github.com/cocos2d/cocos2d-x/pull/10829
https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/107

**Comment by stammen** [comment]
This is in cocos2d-x v3.6 release
