### ISSUE TITLE
Cocos2d-x JSB aka Cocos2d-JS Windows phone support

### ISSUE THREAD

**Issue by edudemy** [MSOpenTech/cocos2d-x#48]
Microsoft Open Technologies, Inc.﻿ Should also port ( & Maintain!) Cocos2d-JS (SpiderMonkey javascript engine) to Windows Phone﻿, since cocos2d-js supports only iOS, Android, Mac, Win Desktops currently. https://github.com/ricardoquesada/Spidermonkey/tree/master/js/src/build-win32

**Comment by stammen** [comment]
JavaScript support was added in cocos2d-x v3.5 and v3.6.
