### ISSUE TITLE
Render Texture Issue in V3 Branch

### ISSUE THREAD

**Issue by waqasanwar79** [MSOpenTech/cocos2d-x#60]
Hi Stammen !

I tried cocos2d-x V3 branch.

I added this code in the end of HelloWorld::init() in the given sample.

CCRenderTexture* renderTexture = CCRenderTexture::create(size.width, size.height);
renderTexture->setPosition(ccp(size.width/2,size.height/2));
this->addChild(renderTexture,10);

I press home button and come back.
![wp_ss_20140708_0001](https://cloud.githubusercontent.com/assets/5887417/3439313/61327ff6-00e2-11e4-8574-2462aa339fa3.png)
![wp_ss_20140708_0002](https://cloud.githubusercontent.com/assets/5887417/3439314/6132c114-00e2-11e4-98d6-84b32e4d5fa0.png)

Render texture issue is not fully resolved as you can see.

**Comment by stammen** [comment]
We have ended support for WP8 with cocos2d-x v3.5. This won't be fixed.
