### ISSUE TITLE
Lack of documentation for WP8

### ISSUE THREAD

**Issue by stammen** [MSOpenTech/cocos2d-x#66]
Lack of documentation on:
o   how .Net and C++ projects work together in the solution.
o   WP8 development training materials.
o   SQLite support on WP8.

**Comment by stammen** [comment]
Duplicate of https://github.com/MSOpenTech/cocos2d-x/issues/145

**Comment by umair6** [comment]
@stammen @qjhd554  Any update on this? I am sure, many developers are waiting to hear on this.
