### ISSUE TITLE
Characters / numbers are not rendered properly

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#74]
There are issues with letters dropping out of words when there are frequent changes to the words, numbers (like if there is a counter, or the app is too busy to render words properly).
![image](https://cloud.githubusercontent.com/assets/6464667/4341851/217ce202-403e-11e4-9472-4547e7331c28.png)

![image](https://cloud.githubusercontent.com/assets/6464667/4341971/4f168f14-403f-11e4-909b-a8c9b461b13d.png)

Reproduced in v3.2 on Nokia Lumia 1520 in the following tests:

a.	Box2d - TestBed: Why the test names don't show correctly (e.g. "T  b  r" instead of Tumbler). 
b.	EventDispatcher: Testing Director Events: numbers are blinking, not showing properly and no labels display for them.
c.     Effects Basic: letters start to drop out of the test names after going through a few tests; 
d.	Extensions-> CCControlButtonTest - only a few letters show when moving control

**Comment by stammen** [comment]
This is in the WP8 Angle code. We are dropping WP8 support. Won't fix.
