### ISSUE TITLE
Test Suite "Audio - NewAudioEngine" is missing in WP8 TestCpp

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#83]
Test Suite "Audio - NewAudioEngine" is missing in WP8 TestCpp (WP8-v3.3)

Tested using Cocos v3 for WP8 device (Nokia Lumia 1520)

Steps to reproduce:
1. Run TestCpp from cocos2d-x v3 on device 
2. Select "Audio - CocosDenshion" test and click play
3. Try changing Pitch, Pan, Gain, touch 'play' and listen to the piece

Actual result: there is no noticeable effect on audio from changing the controls

Note: Only Music Volume can be controlled successfully

**Comment by stammen** [comment]
This will be added in cocos2d-x v3.7.

**Comment by stammen** [comment]
Test suite is in Windows 8.1 Universal App and Windows 10. No support for WP8
