### ISSUE TITLE
Significant frame rate drop for "Logo Smash" test after Toggle debug

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#89]
Tested on Nokia Lumia 1520 in wp8-v3-fix

1. Run Cpp-tests > Node: Physics> "Logo Smash" test (framerate is 46-53 on average)
2. Tap on the 'Toggle debug' control

Actual result: Frame rate drops to 12-15
Expected result: should remain same (this is what I see for other tests with Toggle debug option)

**Comment by stammen** [comment]
This is in the WP8 Angle code. We are dropping WP8 support. Won't fix.
