### ISSUE TITLE
Test Name not rendered correctly after removing all listeners and taking app into background

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#91]
Version: wp8-v3-fix
Device: Nokia Lumia 1520

Steps:
1.     EventDispatcher > Issue 4129: Remove All Listeners
2.     Tap on the “Remove All Listeners”
3.     Press the Start button
4.     Press the back button

Result: squares displayed instead of letters
 
Note: does not reproduce without step 2. Does not reproduce on Android either.
 
![image](https://cloud.githubusercontent.com/assets/6464667/4514040/8f668ac6-4b5a-11e4-90cd-a68c0c28d3d1.png)

**Comment by stammen** [comment]
This is in the WP8 Angle code. We are dropping WP8 support. Won't fix.
