### ISSUE TITLE
Armature performance test crashes when armature count is too high (20000 and up)

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#92]
Device: Nokia Lumia 1520, 
branch: wp8-v3-fix

1. Run cpp-test > Extenstions > CocosStudioArmatureTest > Test Performance
2. Tap on the '+' sign to increase Current Armature Count to 20000 

Result: app crashes

**Comment by stammen** [comment]
This is a limitation of angle.
