### ISSUE TITLE
'Touch the screen' test hangs cpp-test app

### ISSUE THREAD

**Issue by SvDyer** [MSOpenTech/cocos2d-x#93]
Device: Nokia Lumia 1520, 
branch: wp8-v3-fix

1. Run cpp-test > Node: RenderTexture > Touch the screen 
2. Using your finger(s) draw a few lines or circles 

Actual result: App freezes (unable to clear image or move to another test) for a few minutes. Returns to life after some time if left untouched, but if switched to background mode, the app is unable to resume.

Note: Frame Rate for the test drops to 1 or 2 with GL verts value rapidly rising to 1 mln after just a few circles on the screen. (In Android, I can practically color in the whole screen and neither GL verts, nor frame rate metrics are impacted this way)

**Comment by stammen** [comment]
This appears to be working fine in cocos2d-x v3.6

**Comment by stammen** [comment]
This is fixed in cocos2d-x v3.6. Please reopen if you find any issues.
