### ISSUE TITLE
Crash analytics

### ISSUE THREAD

**Issue by jleszczynski** [MSOpenTech/cocos2d-x#96]
Hi,
it is possible to track crashes that occured on C++ side?

In my WP admin dashboard crashes from C# code contain stack trace, but ones from C++ doesn't contain helpful data:

NULL_CLASS_PTR_READ
0        xComponent.dll                                                                                                                      0x00026a14    
1        xComponent.dll                                                                                                                      0x000b727e

(xComponent is name of my project)

How can we catch these?

**Comment by stammen** [comment]
You can try http://azure.microsoft.com/en-us/services/application-insights/
